protocols = imap pop3 lmtp
listen = *, ::

ssl = required
ssl_cert = </etc/letsencrypt/live/quuux.org/fullchain.pem
ssl_key = </etc/letsencrypt/live/quuux.org/privkey.pem
ssl_min_protocol = TLSv1.2

mail_location = maildir:~/Maildir
mail_privileged_group = mail

auth_mechanisms = plain login

passdb {
  driver = pam
}

userdb {
  driver = passwd
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0666
    user = postfix
    group = postfix
  }
  unix_listener auth-userdb {
    mode = 0600
  }
}

service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}
